
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageRoom = new javax.swing.JButton();
        btnCustomerCheckIn = new javax.swing.JButton();
        btnCustomerCheckOut = new javax.swing.JButton();
        btnCustomerDetailsBill = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageRoom.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnManageRoom.setForeground(new java.awt.Color(102, 0, 51));
        btnManageRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage room.png"))); // NOI18N
        btnManageRoom.setText("Manage Room");
        btnManageRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        btnCustomerCheckIn.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnCustomerCheckIn.setForeground(new java.awt.Color(102, 0, 51));
        btnCustomerCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Registration & Check IN.png"))); // NOI18N
        btnCustomerCheckIn.setText("Customer Check In");
        btnCustomerCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerCheckInActionPerformed(evt);
            }
        });
        getContentPane().add(btnCustomerCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        btnCustomerCheckOut.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnCustomerCheckOut.setForeground(new java.awt.Color(102, 0, 51));
        btnCustomerCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Check Out.png"))); // NOI18N
        btnCustomerCheckOut.setText("Customer Check Out");
        btnCustomerCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerCheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnCustomerCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        btnCustomerDetailsBill.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnCustomerDetailsBill.setForeground(new java.awt.Color(102, 0, 51));
        btnCustomerDetailsBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Details Bill.png"))); // NOI18N
        btnCustomerDetailsBill.setText("Customer Details Bill");
        btnCustomerDetailsBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerDetailsBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnCustomerDetailsBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        btnLogout.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(102, 0, 51));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, -1, -1));

        btnExit.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(102, 0, 51));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("RANI Hotel Management System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Homepage.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do you really want to close Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnManageRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRoomActionPerformed
        // TODO add your handling code here:
        new manageRoom().setVisible(true);
    }//GEN-LAST:event_btnManageRoomActionPerformed

    private void btnCustomerCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerCheckInActionPerformed
        // TODO add your handling code here:
        new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_btnCustomerCheckInActionPerformed

    private void btnCustomerCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerCheckOutActionPerformed
        // TODO add your handling code here:
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_btnCustomerCheckOutActionPerformed

    private void btnCustomerDetailsBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerDetailsBillActionPerformed
        // TODO add your handling code here:
        new CustomerDetailsBill().setVisible(true);
    }//GEN-LAST:event_btnCustomerDetailsBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerCheckIn;
    private javax.swing.JButton btnCustomerCheckOut;
    private javax.swing.JButton btnCustomerDetailsBill;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
